name: Upload Release Artifact

on:
  release:
    types:
      - published

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip release]')"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build the application
        run: |
          npm ci
          npm run build

      - name: Prepare Release Artifact
        run: |
          jq .version lerna.json > dist/version.txt
          cd dist/
          zip -r ../app.zip .
          cd ..

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
